<div class="dashboard-wrapper">
<div class="container-fluid  dashboard-content">
    <div class="row">
        <div class="col-xl-4 col-lg-4 col-md-12 col-sm-12 col-12">
            <div class="page-header">
                <h2 class="pageheader-title">Leads List View</h2>
                <p class="pageheader-text"></p>
                <div class="page-breadcrumb">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#" class="breadcrumb-link">Dashboard</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Leads List View</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>

        <div class="col-xl-3 col-lg-3 col-md-12 col-sm-12 col-12">
            <a href="<?php echo base_url('assets/leads_demo.csv'); ?>" class="btn btn-success d-none d-lg-block" download>
                <i class="ti-import"></i> Sample File for import leads
            </a>
        </div>

        <div class="col-xl-5 col-lg-5 col-md-12 col-sm-12 col-12">
        <form accept-charset="utf-8" role="form" method="post" id="import_form" enctype="multipart/form-data" action="<?php echo base_url('insertdb/import'); ?>">
            <div class="form-group">
                <label for="site_name" class="col-sm-3 control-label">Select File</label>
                <div class="col-sm-9">
                    <div class="input file required">
                        <input type="file" name="file" id="file" required>
                    </div>                       
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group text-left">
                    <div class="col-sm-offset-3 col-sm-7">
                        <button type="submit" class="btn btn-success">
                            <span class="ti-export"></span>&nbsp;Import Contacts</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
    </div>


    <div class="row">
        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
            <div class="card">
                <h5 class="card-header">
                    <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 col-12">
                        <a href="<?php echo base_url('add_leads'); ?>" class="btn btn-rounded btn-primary">Add</a>
                    </div>
                </h5>
                <div class="card-body">

                    <div class="simple-outline-card">
                        <ul class="nav nav-tabs" id="myTab6" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active border-left-0" id="home-tab-simple-outline" data-toggle="tab" href="#home-simple-outline" role="tab" aria-controls="home" aria-selected="true">Today Leads</a>
                            </li>
                            <li class="nav-item" style="display: none;">
                                <a class="nav-link" id="profile-tab-simple-outline" data-toggle="tab" href="#profile-simple-outline" role="tab" aria-controls="profile" aria-selected="false">Tomorrow Leads</a>
                            </li>
                            <li class="nav-item" style="display: none;">
                                <a class="nav-link" id="contact-tab-simple-outline" data-toggle="tab" href="#contact-simple-outline" role="tab" aria-controls="contact" aria-selected="false">Upcoming Leads</a>
                            </li>
                        </ul>
                        <div class="tab-content" id="myTabContent6">
                            <div class="tab-pane fade show active" id="home-simple-outline" role="tabpanel" aria-labelledby="home-tab-simple-outline">
                                

                    <div class="table-responsive">
                        <table class="table table-striped table-bordered first">
                            <thead>
                                <tr>
                                    <th>Generated By Name</th>
                                    <th>contact Name</th>
                                    <th>Company Email</th>
                                    <th>Phone</th>
                                    <th>Joined us on</th>
                                    <th>Follow up Date</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
<?php 
    $user_id = getProfileName('user_id');
    if($user_id==1){
        $query_tbl_leads = $this->db->query("SELECT * FROM `tbl_leads` where eDelete=0 ORDER BY `tbl_leads`.`follow_up_date` DESC");
    } else {
        $query_tbl_leads = $this->db->query("SELECT * FROM `tbl_leads` where eDelete=0 and user_id=$user_id ORDER BY `tbl_leads`.`follow_up_date` DESC");
    }
    
    $result_leads = $query_tbl_leads->result_array();
    foreach ($result_leads as $key => $value) {
?>
<tr>
    <td><?php echo $value['lead_generation_name']; ?></td>
    <td><?php echo $value['contact_person_name']; ?></td>
    <td><?php echo $value['company_email']; ?></td>
    <td><?php echo $value['phone_number']; ?></td>
    <td><?php echo date('Y-m-d', strtotime($value['joined_us_on'])); ?></td>
    <td><?php 
    if(date('Y-m-d', strtotime($value['follow_up_date'])) == date("Y-m-d")) 
    { 
        echo date('Y-m-d', strtotime($value['follow_up_date'])); 
    } ?></td>
    <td>
        <a href="<?php echo base_url('leads_edit/'); ?><?php echo $value['lead_id']; ?>" class="btn btn-primary">Edit</a>
    </td>
</tr>
                            <?php } ?>

                            </tbody>
                        </table>
                    </div>

                            </div>
                            <div class="tab-pane fade" id="profile-simple-outline" role="tabpanel" aria-labelledby="profile-tab-simple-outline">
                                

                     <div class="table-responsive">
                        <table class="table table-striped table-bordered first">
                            <thead>
                                <tr>
                                    <th>Generated By Name</th>
                                    <th>Email</th>
                                    <th>Phone</th>
                                    <th>Company Name</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>Tiger Nixon</td>
                                    <td>System Architect</td>
                                    <td>Edinburgh</td>
                                    <td>61</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>

                            </div>
                            <div class="tab-pane fade" id="contact-simple-outline" role="tabpanel" aria-labelledby="contact-tab-simple-outline">
                                

                     <div class="table-responsive">
                        <table class="table table-striped table-bordered first">
                            <thead>
                                <tr>
                                    <th>Generated By Name</th>
                                    <th>Email</th>
                                    <th>Phone</th>
                                    <th>Company Name</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>Tiger Nixon</td>
                                    <td>System Architect</td>
                                    <td>Edinburgh</td>
                                    <td>61</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    
                            </div>
                        </div>
                    </div>
                
                </div>
            </div>
        </div>
    </div>
</div>